---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "/home/rdsisdf/Git/hosts.yaml"
        group_file: "/home/rdsisdf/Git/groups.yaml"
        defaults_file: "/home/rdsisdf/Git/defaults.yaml"
runner:
  plugin: threaded
  options:
    num_workers: 100