---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "/home/rdsisdf/TemplateAutomation/hosts.yaml"
        group_file: "/home/rdsisdf/TemplateAutomation/groups.yaml"
        defaults_file: "/home/rdsisdf/TemplateAutomation/defaults.yaml"
runner:
  plugin: threaded
  options:
    num_workers: 100